#ifndef GAME_INFO_H
#define GAME_INFO_H

#define SCREEN_WIDTH 960
#define SCREEN_HEIGHT 640

#define TILE_WIDTH 40
#define TILE_HEIGHT 40

#define SCREEN_TILE_WIDTH (SCREEN_WIDTH / TILE_WIDTH)
#define SCREEN_TILE_HEIGHT (SCREEN_HEIGHT / TILE_HEIGHT)

#define ITEM_ZORDER 1
#define ENEMY_ZORDER 2
#define PLAYER_ZORDER 3

#endif